import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";
import "./globals.css";
import BottomNavBar from "./components/BottomNavBar";
import "nes.css/css/nes.min.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  weight: ['400'],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${pressStart2P.className} ${geistMono.variable} antialiased`}
        >
         <header className="flex justify-end items-center p-4 gap-4 h-16">
            {/* <SignedOut>
              <SignInButton />
            <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
           </SignedIn> */}
          </header>
          {children}
        </body>
        <BottomNavBar/>
      </html>
    </ClerkProvider>
  );
}